image: gradle:7.5-jdk17
stages:
  - build
  - test

build:
  stage: build
  script:
    - java -version
    - gradle --version
    - echo "Building the project"
    - ./gradlew build # For Gradle
    # - mvn clean package # Uncomment if using Maven
  only:
    - main

test:
  stage: test
  script:
    - echo "Running tests"
    - ./gradlew test # For Gradle
    # - mvn test # Uncomment if using Maven
  only:
    - main