image: gradle:7.5-jdk17
stages:
  - build
  - test
build_stage:
  stage: build
  script:
    - echo "Building the project"
    - java -version
    - gradle --version
    - ./gradlew build
  artifacts:
    paths:
      - ./build
test_stage:
  stage: test
  script:
    - echo "Running tests"
    - test -e build/libs/demo-0.0.1-SNAPSHOT.jar || (echo "Artifact missing";)
    - ./gradlew test